#pragma once
#include "../memoryWork.h"

class monitor_event
{
public:
	static void initGameEvents();
	static void deInitGameEvents();

	static void __thiscall onFactionTurnStart(void* _this, factionStruct* faction);
	static void __thiscall onFactionWarDeclared(void* _this, factionStruct* faction, factionStruct* targetfac);
	static void __thiscall onHordeFormed(void* _this, factionStruct* faction);
	static void __thiscall onFactionTurnEnd(void* _this, factionStruct* faction);
	static void __thiscall onHireMercenaries(void* _this, namedCharacter* character);
	static void __thiscall onGeneralCaptureResidence(void* _this, namedCharacter* character);
	static void __thiscall onGeneralCaptureWonder(void* _this, namedCharacter* character);
	static void __thiscall onGeneralCaptureSettlement(void* _this, namedCharacter* character, settlementStruct* settlement);
	static void __thiscall onLeaderDestroyedFaction(void* _this, namedCharacter* character);
	static void __thiscall onDisaster(void* _this, int_32 disasterType);
	static void __thiscall onCharacterDamagedByDisaster(void* _this, namedCharacter* character, int_32 disasterType);
	static void __thiscall onGeneralAssaultsResidence(void* _this, namedCharacter* character);
	static void __thiscall onOfferedForAdoption(void* _this, namedCharacter* character);
	static void __thiscall onLesserGeneralOfferedForAdoption(void* _this, namedCharacter* character);
	static void __thiscall onOfferedForMarriage(void* _this, namedCharacter* character);
	static void __thiscall onBrotherAdopted(void* _this, namedCharacter* character);
	static void __thiscall onBecomesFactionLeader(void* _this, namedCharacter* character);
	static void __thiscall onBecomesFactionHeir(void* _this, namedCharacter* character);
	static void __thiscall onBecomeQuaestor(void* _this, namedCharacter* character);
	static void __thiscall onBecomeAedile(void* _this, namedCharacter* character);
	static void __thiscall onBecomePraetor(void* _this, namedCharacter* character);
	static void __thiscall onBecomeConsul(void* _this, namedCharacter* character);
	static void __thiscall onBecomeCensor(void* _this, namedCharacter* character);
	static void __thiscall onBecomePontifexMaximus(void* _this, namedCharacter* character);
	static void __thiscall onCeasedFactionLeader(void* _this, namedCharacter* character);
	static void __thiscall onCeasedFactionHeir(void* _this, namedCharacter* character);
	static void __thiscall onCeasedQuaestor(void* _this, namedCharacter* character);
	static void __thiscall onCeasedAedile(void* _this, namedCharacter* character);
	static void __thiscall onCeasedPraetor(void* _this, namedCharacter* character);
	static void __thiscall onCeasedConsul(void* _this, namedCharacter* character);
	static void __thiscall onCeasedCensor(void* _this, namedCharacter* character);
	static void __thiscall onCeasedPontifexMaximus(void* _this, namedCharacter* character);
	static void __thiscall onUngarrisonedFort(void* _this, fortStruct* fort);
	static void __thiscall onLostLegionaryEagle(void* _this, namedCharacter* character);
	static void __thiscall onCapturedLegionaryEagle(void* _this, namedCharacter* character);
//	static void __thiscall onRecapturedLegionaryEagle(void* _this, );
	static void __thiscall onSenateExposure(void* _this, namedCharacter* character);
	static void __thiscall onQuaestorInvestigationMinor(void* _this, namedCharacter* character);
	static void __thiscall onQuaestorInvestigation(void* _this, namedCharacter* character);
	static void __thiscall onQuaestorInvestigationMajor(void* _this, namedCharacter* character);
//	static void __thiscall onPopularSupportForOverthrow(void* _this, );
//	static void __thiscall onSenateReadyToOutlawFaction(void* _this, factionStruct* faction);
	static void __thiscall onSenateOutlawsFaction(void* _this, factionStruct* faction);
	static void __thiscall onCharacterSelected(void* _this, namedCharacter* selectedChar, int_32 action, coords* coords, int_32 region_id);
	static void __thiscall onSettlementSelected(void* _this, settlementStruct* settlement);
	static void __thiscall onMultiTurnMove(void* _this, namedCharacter* character);
	static void __thiscall onCharacterPanelOpen(void* _this, settlementStruct* settlement);
	static void __thiscall onSettlementPanelOpen(void* _this, factionStruct* faction);
	static void __thiscall onFinancesPanelOpen(void* _this, factionStruct* faction);
	static void __thiscall onFactionSummaryPanelOpen(void* _this, factionStruct* faction);
	static void __thiscall onFamilyTreePanelOpen(void* _this, factionStruct* faction);
//	static void __thiscall onDiplomaticStandingPanelOpen(void* _this);
//	static void __thiscall onSenateMissionsPanelOpen(void* _this, factionStruct* faction);
	static void __thiscall onSenateOfficesPanelOpen(void* _this, int param_2);
	static void __thiscall onDiplomacyPanelOpen(void* _this, factionStruct* faction);
	static void __thiscall onPreBattlePanelOpen(void* _this, factionStruct* faction);
//	static void __thiscall onRecruitmentPanelOpen(void* _this, settlementStruct* settlement);
//	static void __thiscall onConstructionPanelOpen(void* _this, settlementStruct* settlement);
	static void __thiscall onTradePanelOpen(void* _this, settlementStruct* settlement);
//	static void __thiscall onHireMercenariesPanelOpen(void* _this);
//	static void __thiscall onNavalAutoResolvePanelOpen(void* _this);
	static void __thiscall onIncomingMessage(void* _this, int eventID);
	static void __thiscall onMessageOpen(void* _this, int eventID);
	static void __thiscall onRequestBuildingAdvice(void* _this, settlementStruct* settlement, char* resourceDescription);
	static void __thiscall onRequestTrainingAdvice(void* _this, settlementStruct* settlement, char* resourceDescription);
//	static void __thiscall onRequestMercenariesAdvice(void* _this, stackStruct* army);
	static void __thiscall onButtonPressed(void* _this, char* resourceDescription);
	static void __thiscall onShortcutTriggered(void* _this, char* resourceDescription, char* id);
	static void __thiscall onScrollOpened(void* _this, char* resourceDescription);
	static void __thiscall onScrollClosed(void* _this, char* resourceDescription);
//	static void __thiscall onAdviceSupressed(void* _this, char* resourceDescription);
	static void __thiscall onScrollAdviceRequested(void* _this, char* resourceDescription);
//	static void __thiscall onPreBattleScrollAdviceRequested(void* _this);
//	static void __thiscall onNavalPreBattleScrollAdviceRequested(void* _this);
	static void __thiscall onSettlementScrollAdviceRequested(void* _this, settlementStruct* settlement);
//	static void __thiscall onIdle(void* _this);
//	static void __thiscall onAbandonShowMe(void* _this);
//	static void __thiscall onScriptedAdvice(void* _this);
//	static void __thiscall onDeclineAutomatedSettlementManagement(void* _this, factionStruct* faction, settlementStruct* settlement);
//	static void __thiscall onEscPressed(void* _this);
	static void __thiscall onGameReloaded(void* _this);
	static void __thiscall onSettlementTurnStart(void* _this, settlementStruct* settlement);
	static void __thiscall onSettlementTurnEnd(void* _this, settlementStruct* settlement);
	static void __thiscall onNewAdmiralCreated(void* _this, settlementStruct* settlement, namedCharacter* character);
	static void __thiscall onUnitTrained(void* _this, factionStruct* faction, settlementStruct* settlement, unit* trainedUnit);
	static void __thiscall onGovernorUnitTrained(void* _this, namedCharacter* character, settlementStruct* settlement, unit* trainedUnit);
	static void __thiscall onBuildingCompleted(void* _this, settlementStruct* settlement, factionStruct* faction, eventBuild* evBuild);
	static void __thiscall onGovernorBuildingCompleted(void* _this, namedCharacter* character, settlementStruct* settlement, eventBuild* evBuild);
//	static void __thiscall onPlugInCompleted(void* _this, settlementStruct* settlement, eventBuild* evBuild);
//	static void __thiscall onGovernorPlugInCompleted(void* _this, namedCharacter* character, eventBuild* evBuild);
	static void __thiscall onAgentCreated(void* _this, namedCharacter* character, enum characterType type, settlementStruct* settlement);
	static void __thiscall onGovernorAgentCreated(void* _this, namedCharacter* character, enum characterType type, settlementStruct* settlement);
	static void __thiscall onBuildingDestroyed(void* _this, namedCharacter* settlement);
	static void __thiscall onGovernorBuildingDestroyed(void* _this, namedCharacter* character);
	static void __thiscall onCityRiots(void* _this, settlementStruct* settlement, factionStruct* faction);
	static void __thiscall onGovernorCityRiots(void* _this, namedCharacter* character, settlementStruct* settlement, factionStruct* faction);
	static void __thiscall onCityRebels(void* _this, settlementStruct* settlement, factionStruct* faction);
	static void __thiscall onGovernorCityRebels(void* _this, namedCharacter* character, settlementStruct* settlement, factionStruct* faction);
	static void __thiscall onGovernorThrowGames(void* _this, namedCharacter* character, settlementStruct* settlement);
	static void __thiscall onGovernorThrowRaces(void* _this, namedCharacter* character, settlementStruct* settlement);
	static void __thiscall onUngarrisonedSettlement(void* _this, settlementStruct* settlement);
	static void __thiscall onEnslavePopulation(void* _this, namedCharacter* character, factionStruct* faction);
	static void __thiscall onExterminatePopulation(void* _this, namedCharacter* character);
	static void __thiscall onCitySacked(void* _this, settlementStruct* settlement, factionStruct* faction);
	static void __thiscall onPreBattle(void* _this, namedCharacter* nc);
	static void __thiscall onPreBattleWithdrawal(void* _this, namedCharacter* nc);
	static void __thiscall onBattleAiCommenced(void* _this, factionStruct* faction);
	static void __thiscall onBattleDelayPhaseCommenced(void* _this, factionStruct* faction);
	static void __thiscall onBattleDeploymentPhaseCommenced(void* _this, factionStruct* faction);
	static void __thiscall onBattleConflictPhaseCommenced(void* _this, factionStruct* faction);
	static void __thiscall onBattlePlayerUnitAttacksEnemyUnit(void* _this, unit* attacker, unit* defender);
	static void __thiscall onBattleEnemyUnitAttacksPlayerUnit(void* _this, unit* attacker, unit* defender);
	static void __thiscall onBattlePlayerAttacksSettlementBuilding(void* _this, unit* unit, buildingBattle* building);
	static void __thiscall onBattleEnemyAttacksSettlementBuilding(void* _this, unit* unit, buildingBattle* building);
	static void __thiscall onBattleUnitGoesBerserk(void* _this, unit* unit);
	static void __thiscall onBattlePlayerUnitGoesBerserk(void* _this, unit* unit);
	static void __thiscall onBattleEnemyUnitGoesBerserk(void* _this, unit* unit);
	static void __thiscall onBattleUnitRouts(void* _this, unit* unit);
	static void __thiscall onBattlePlayerUnitRouts(void* _this, unit* unit);
	static void __thiscall onBattleEnemyUnitRouts(void* _this, unit* unit);
	static void __thiscall onBattlePlayerSiegeEngineDestroyed(void* _this, siegeEngine* engine);
	static void __thiscall onBattleEnemySiegeEngineDestroyed(void* _this, siegeEngine* engine);
	static void __thiscall onPostBattle(void* _this, namedCharacter* nc);
	static void __thiscall onBattleArmyRouted(void* _this, stackStruct* army);
	static void __thiscall onBattleGeneralKilled(void* _this, character* character);
	static void __thiscall onBattleGeneralRouted(void* _this, character* character);
	static void __thiscall onBattleReinforcementsArrive(void* _this, stackStruct* army);
	static void __thiscall onBattleSiegeEngineDestroyed(void* _this, siegeEngine* engine);
	static void __thiscall onBattleSiegeEngineDocksWall(void* _this, unit* unit);
	static void __thiscall onBattleGatesAttackedByEngine(void* _this, siegeEngine* engine, buildingBattle* building);
	static void __thiscall onBattleGatesAttackedByPlayerEngine(void* _this, siegeEngine* engine, buildingBattle* building);
	static void __thiscall onBattleGatesAttackedByEnemyEngine(void* _this, siegeEngine* engine, buildingBattle* building);
	static void __thiscall onBattleBattleGatesDestroyedByEngine(void* _this, siegeEngine* engine, buildingBattle* gates);
	static void __thiscall onBattleWallsBreachedByEngine(void* _this, siegeEngine* engine, buildingBattle* wall);
	static void __thiscall onBattleWallsCaptured(void* _this, buildingBattle* building, unit* unit);
	static void __thiscall onBattleFinished(void* _this, battleSide* side, int reason, int result, int rating);
	static void __thiscall onBirth(void* _this, namedCharacter* nc);
	static void __thiscall onCharacterComesOfAge(void* _this, namedCharacter* nc);
	static void __thiscall onCharacterMarries(void* _this, namedCharacter* nc);
	static void __thiscall onCharacterBecomesAFather(void* _this, namedCharacter* nc);
	static void __thiscall onCharacterTurnStart(void* _this, namedCharacter* nc);
	static void __thiscall onCharacterTurnEnd(void* _this, namedCharacter* nc, settlementStruct* settlement);
	static void __thiscall onCharacterTurnEndInSettlement(void* _this, namedCharacter* nc, settlementStruct* settlement);
	static void __thiscall onGeneralDevastatesTile(void* _this, namedCharacter* nc);
	static void __thiscall onSpyMission(void* _this, namedCharacter* nc, factionStruct* faction, missionEnum m);
	static void __thiscall onExecutesASpyOnAMission(void* _this, namedCharacter* nc);
	static void __thiscall onLeaderOrderedSpyingMission(void* _this, namedCharacter* nc, factionStruct* faction, missionEnum m);
	static void __thiscall onAssassinationMission(void* _this, namedCharacter* nc, missionEnum m);
	static void __thiscall onExecutesAnAssassinOnAMission(void* _this, namedCharacter* nc);
	static void __thiscall onLeaderOrderedAssassination(void* _this, namedCharacter* leader, namedCharacter* target, missionEnum m);
	static void __thiscall onSufferAssassinationAttempt(void* _this, namedCharacter* nc);
	static void __thiscall onSabotageMission(void* _this, namedCharacter* nc, missionEnum m);
	static void __thiscall onLeaderOrderedSabotage(void* _this, namedCharacter* nc);
	static void __thiscall onBriberyMission(void* _this, namedCharacter* nc, factionStruct* target, missionEnum m);
	static void __thiscall onLeaderOrderedBribery(void* _this, namedCharacter* nc);
	static void __thiscall onAcceptBribe(void* _this, namedCharacter* nc);
	static void __thiscall onRefuseBribe(void* _this, namedCharacter* nc);
	static void __thiscall onInsurrection(void* _this, namedCharacter* nc);
	static void __thiscall onDiplomacyMission(void* _this, namedCharacter* nc, factionStruct* faction, missionEnum m);
	static void __thiscall onLeaderOrderedDiplomacy(void* _this, namedCharacter* nc);
	static void __thiscall onLeaderSenateMissionSuccess(void* _this, namedCharacter* nc);
	static void __thiscall onLeaderSenateMissionFailed(void* _this, namedCharacter* nc);
};








